[project]
name = "yarpc"
version = "0.1.0"
classifiers = ["Private :: Do not Upload"]
description = "Yet another remote procedure call generator"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "", email = "dummy@mail.com"},
]
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "jsonschema>=4.26.0",
    "pyyaml>=6.0.3",
]

[project.scripts]
yarpc = "yarpc.main:main"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
