# Generated by YARPC
# Version:  0.1.0+editable
# Spec:
#   File: /workspace/tests/specs/05.2_dictionaries_with_structs.yml
#   Object: SimonsDict
#   Template: py/struct.j2

from .struct_dict import StructDict
from dataclasses import dataclass
from typing import List, Dict

@dataclass
class SimonsDict:
    """
    A struct containing dicts

    Args:
        numbers (Dict[str, StructDict]): some struct dicts
    """
    numbers: Dict[str, StructDict]

    def to_dbus(self):
        """
        Marshals this object into an array compatible with dbus structs.

        Returns:
            list: the marshalled structure
        """
        return [
            { k0: v0.to_dbus() for k0, v0 in self.numbers.items() },
        ]

    def from_dbus(dbus_struct: list):
        """
        Attempts to unmarshal a D-Bus struct array into this dataclass

        Args:
            dbus_struct (list): the marshalled D-Bus struct as array

        Returns:
            SimonsDict: the unmarshalled structure
        """
        return SimonsDict(
            numbers={ k0: StructDict.from_dbus(v0) for k0, v0 in dbus_struct[0].items() },
        )
