# Generated by YARPC
# Version:  0.1.0
# Definition:
#   File: /workspace/tests/definitions/qt6/07_qml_instantiation.yml
#   Object: QmlEnum
#   Template: py/enum.j2

from enum import Enum

class QmlEnum(Enum):
    """
    an enum
    """
    ONE = 1
    TWO = 2
    ENO = -1
    OWT = -2
