[project]
name = "python_service"
version = "0.1.0"
classifiers = ["Private :: Do not Upload"]
description = "Python D-Bus service"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "", email = "dummy@mail.com"},
]
requires-python = ">=3.12"
dependencies = [
    "dbus-next>=0.2.3",
]

[project.scripts]
py_service = "python_service.main:main"

[tool.uv]
package = true
