// Generated by YARPC
// Version:  0.1.0
// Definition:
//   File: /workspace/tests/definitions/02.2_primitives.yml
//   Object: Primitives
//   Template: rust/client.j2

#![allow(dead_code)]

use std::sync::Arc;
use dbus::nonblock::{SyncConnection, MsgMatch, Proxy};
use dbus::message::{Message, MatchRule};
use dbus::arg::ReadAll;
use super::connection::{connect, close};

/**
   D-Bus client for the com.yarpc.backend.primitives D-Bus interface
 */
pub struct BackendPrimitivesClient {
    connection: Option<Arc<SyncConnection>>,
    timeout: std::time::Duration,
    signal_handlers: Vec<MsgMatch>,
}

impl BackendPrimitivesClient {

    /**
       Configures the D-Bus connection.
       Sets connection timeout to 5s.

       Timeout determines how long a connection attempt
       during a method call may take before panicking.
     */
    pub async fn connect() -> Result<Self, dbus::Error> {
        BackendPrimitivesClient::connect_timeout(std::time::Duration::from_secs(5)).await
    }

    /**
       Configures the D-Bus connection.

       Timeout determines how long a connection attempt
       during a method call may take before panicking.
     */
    pub async fn connect_timeout(timeout: std::time::Duration) -> Result<Self, dbus::Error> {
        let connection = connect().await?;
        Ok(Self{connection: Some(connection), timeout, signal_handlers: Vec::new()})
    }


    /**
       Disconnects client from D-Bus
     */
    pub async fn close(&mut self) -> Result<(), dbus::Error> {
        if self.connection.is_some() {
           for s in &self.signal_handlers {
                self.connection.as_ref().unwrap().remove_match(s.token()).await?;
            }
        }
        self.connection = None;
        let _ = close().await;
        Ok(())
    }

    pub async fn remove_signal_handler(&mut self, token: dbus::channel::Token)-> Result<(), dbus::Error> {
        let idx = self.signal_handlers.iter().position(|x| x.token() == token);
        match (idx, &self.connection) {
            (Some(i), Some(c)) => {
                self.signal_handlers.remove(i);
                c.remove_match(token).await
            }
            _ => Err(dbus::Error::new_failed("Client not connected to D-Bus or token invalid")),
        }
    }

    /**
        Set handler for Uint8Signal signal

        Args:
            handler: the signal handler
     */
    pub async fn on_uint8_signal<R: ReadAll, F: FnMut(Message, R) -> bool + Send + 'static>(&mut self, f: F) -> Result<dbus::channel::Token, dbus::Error> {
        match &self.connection {
            Some(c) => {
                let mr = MatchRule::new_signal("com.yarpc.backend.primitives", "Uint8Signal");
                let signal_matcher = c.add_match(mr).await?.cb(f);
                let token = signal_matcher.token();
                self.signal_handlers.push(signal_matcher);
                Ok(token)
            },
            None => Err(dbus::Error::new_failed("Client not connected to D-Bus")),
        }
    }
    /**
        Set handler for BoolSignal signal

        Args:
            handler: the signal handler
     */
    pub async fn on_bool_signal<R: ReadAll, F: FnMut(Message, R) -> bool + Send + 'static>(&mut self, f: F) -> Result<dbus::channel::Token, dbus::Error> {
        match &self.connection {
            Some(c) => {
                let mr = MatchRule::new_signal("com.yarpc.backend.primitives", "BoolSignal");
                let signal_matcher = c.add_match(mr).await?.cb(f);
                let token = signal_matcher.token();
                self.signal_handlers.push(signal_matcher);
                Ok(token)
            },
            None => Err(dbus::Error::new_failed("Client not connected to D-Bus")),
        }
    }
    /**
        Set handler for Int16Signal signal

        Args:
            handler: the signal handler
     */
    pub async fn on_int16_signal<R: ReadAll, F: FnMut(Message, R) -> bool + Send + 'static>(&mut self, f: F) -> Result<dbus::channel::Token, dbus::Error> {
        match &self.connection {
            Some(c) => {
                let mr = MatchRule::new_signal("com.yarpc.backend.primitives", "Int16Signal");
                let signal_matcher = c.add_match(mr).await?.cb(f);
                let token = signal_matcher.token();
                self.signal_handlers.push(signal_matcher);
                Ok(token)
            },
            None => Err(dbus::Error::new_failed("Client not connected to D-Bus")),
        }
    }
    /**
        Set handler for Uint16Signal signal

        Args:
            handler: the signal handler
     */
    pub async fn on_uint16_signal<R: ReadAll, F: FnMut(Message, R) -> bool + Send + 'static>(&mut self, f: F) -> Result<dbus::channel::Token, dbus::Error> {
        match &self.connection {
            Some(c) => {
                let mr = MatchRule::new_signal("com.yarpc.backend.primitives", "Uint16Signal");
                let signal_matcher = c.add_match(mr).await?.cb(f);
                let token = signal_matcher.token();
                self.signal_handlers.push(signal_matcher);
                Ok(token)
            },
            None => Err(dbus::Error::new_failed("Client not connected to D-Bus")),
        }
    }
    /**
        Set handler for Int32Signal signal

        Args:
            handler: the signal handler
     */
    pub async fn on_int32_signal<R: ReadAll, F: FnMut(Message, R) -> bool + Send + 'static>(&mut self, f: F) -> Result<dbus::channel::Token, dbus::Error> {
        match &self.connection {
            Some(c) => {
                let mr = MatchRule::new_signal("com.yarpc.backend.primitives", "Int32Signal");
                let signal_matcher = c.add_match(mr).await?.cb(f);
                let token = signal_matcher.token();
                self.signal_handlers.push(signal_matcher);
                Ok(token)
            },
            None => Err(dbus::Error::new_failed("Client not connected to D-Bus")),
        }
    }
    /**
        Set handler for Uint32Signal signal

        Args:
            handler: the signal handler
     */
    pub async fn on_uint32_signal<R: ReadAll, F: FnMut(Message, R) -> bool + Send + 'static>(&mut self, f: F) -> Result<dbus::channel::Token, dbus::Error> {
        match &self.connection {
            Some(c) => {
                let mr = MatchRule::new_signal("com.yarpc.backend.primitives", "Uint32Signal");
                let signal_matcher = c.add_match(mr).await?.cb(f);
                let token = signal_matcher.token();
                self.signal_handlers.push(signal_matcher);
                Ok(token)
            },
            None => Err(dbus::Error::new_failed("Client not connected to D-Bus")),
        }
    }
    /**
        Set handler for Int64Signal signal

        Args:
            handler: the signal handler
     */
    pub async fn on_int64_signal<R: ReadAll, F: FnMut(Message, R) -> bool + Send + 'static>(&mut self, f: F) -> Result<dbus::channel::Token, dbus::Error> {
        match &self.connection {
            Some(c) => {
                let mr = MatchRule::new_signal("com.yarpc.backend.primitives", "Int64Signal");
                let signal_matcher = c.add_match(mr).await?.cb(f);
                let token = signal_matcher.token();
                self.signal_handlers.push(signal_matcher);
                Ok(token)
            },
            None => Err(dbus::Error::new_failed("Client not connected to D-Bus")),
        }
    }
    /**
        Set handler for Uint64Signal signal

        Args:
            handler: the signal handler
     */
    pub async fn on_uint64_signal<R: ReadAll, F: FnMut(Message, R) -> bool + Send + 'static>(&mut self, f: F) -> Result<dbus::channel::Token, dbus::Error> {
        match &self.connection {
            Some(c) => {
                let mr = MatchRule::new_signal("com.yarpc.backend.primitives", "Uint64Signal");
                let signal_matcher = c.add_match(mr).await?.cb(f);
                let token = signal_matcher.token();
                self.signal_handlers.push(signal_matcher);
                Ok(token)
            },
            None => Err(dbus::Error::new_failed("Client not connected to D-Bus")),
        }
    }
    /**
        Set handler for DoubleSignal signal

        Args:
            handler: the signal handler
     */
    pub async fn on_double_signal<R: ReadAll, F: FnMut(Message, R) -> bool + Send + 'static>(&mut self, f: F) -> Result<dbus::channel::Token, dbus::Error> {
        match &self.connection {
            Some(c) => {
                let mr = MatchRule::new_signal("com.yarpc.backend.primitives", "DoubleSignal");
                let signal_matcher = c.add_match(mr).await?.cb(f);
                let token = signal_matcher.token();
                self.signal_handlers.push(signal_matcher);
                Ok(token)
            },
            None => Err(dbus::Error::new_failed("Client not connected to D-Bus")),
        }
    }
    /**
        Set handler for StringSignal signal

        Args:
            handler: the signal handler
     */
    pub async fn on_string_signal<R: ReadAll, F: FnMut(Message, R) -> bool + Send + 'static>(&mut self, f: F) -> Result<dbus::channel::Token, dbus::Error> {
        match &self.connection {
            Some(c) => {
                let mr = MatchRule::new_signal("com.yarpc.backend.primitives", "StringSignal");
                let signal_matcher = c.add_match(mr).await?.cb(f);
                let token = signal_matcher.token();
                self.signal_handlers.push(signal_matcher);
                Ok(token)
            },
            None => Err(dbus::Error::new_failed("Client not connected to D-Bus")),
        }
    }
    /**
        a method

        Args:
            value: the value

        Returns:
            the return type
     */
    pub async fn uint8_method(&self, value: u8, ) -> Result<(u8,), dbus::MethodErr> {
        match &self.connection {
            Some(c) => {
                let proxy = Proxy::new("com.yarpc.backend", "/com/yarpc/backend/withArgs", self.timeout, c.clone());
                match proxy.method_call::<(u8,), (u8, ), _, _>("com.yarpc.backend.primitives", "Uint8Method", (value, )).await {
                    Ok(r) => Ok(r),
                    Err(e) => Err(dbus::MethodErr::from(e))
                }
            },
            None => Err(dbus::MethodErr::failed("Client not connected to D-Bus")),
        }
    }
    /**
        a method

        Args:
            value: the value

        Returns:
            the return type
     */
    pub async fn bool_method(&self, value: bool, ) -> Result<(bool,), dbus::MethodErr> {
        match &self.connection {
            Some(c) => {
                let proxy = Proxy::new("com.yarpc.backend", "/com/yarpc/backend/withArgs", self.timeout, c.clone());
                match proxy.method_call::<(bool,), (bool, ), _, _>("com.yarpc.backend.primitives", "BoolMethod", (value, )).await {
                    Ok(r) => Ok(r),
                    Err(e) => Err(dbus::MethodErr::from(e))
                }
            },
            None => Err(dbus::MethodErr::failed("Client not connected to D-Bus")),
        }
    }
    /**
        a method

        Args:
            value: the value

        Returns:
            the return type
     */
    pub async fn int16_method(&self, value: i16, ) -> Result<(i16,), dbus::MethodErr> {
        match &self.connection {
            Some(c) => {
                let proxy = Proxy::new("com.yarpc.backend", "/com/yarpc/backend/withArgs", self.timeout, c.clone());
                match proxy.method_call::<(i16,), (i16, ), _, _>("com.yarpc.backend.primitives", "Int16Method", (value, )).await {
                    Ok(r) => Ok(r),
                    Err(e) => Err(dbus::MethodErr::from(e))
                }
            },
            None => Err(dbus::MethodErr::failed("Client not connected to D-Bus")),
        }
    }
    /**
        a method

        Args:
            value: the value

        Returns:
            the return type
     */
    pub async fn uint16_method(&self, value: u16, ) -> Result<(u16,), dbus::MethodErr> {
        match &self.connection {
            Some(c) => {
                let proxy = Proxy::new("com.yarpc.backend", "/com/yarpc/backend/withArgs", self.timeout, c.clone());
                match proxy.method_call::<(u16,), (u16, ), _, _>("com.yarpc.backend.primitives", "Uint16Method", (value, )).await {
                    Ok(r) => Ok(r),
                    Err(e) => Err(dbus::MethodErr::from(e))
                }
            },
            None => Err(dbus::MethodErr::failed("Client not connected to D-Bus")),
        }
    }
    /**
        a method

        Args:
            value: the value

        Returns:
            the return type
     */
    pub async fn int32_method(&self, value: i32, ) -> Result<(i32,), dbus::MethodErr> {
        match &self.connection {
            Some(c) => {
                let proxy = Proxy::new("com.yarpc.backend", "/com/yarpc/backend/withArgs", self.timeout, c.clone());
                match proxy.method_call::<(i32,), (i32, ), _, _>("com.yarpc.backend.primitives", "Int32Method", (value, )).await {
                    Ok(r) => Ok(r),
                    Err(e) => Err(dbus::MethodErr::from(e))
                }
            },
            None => Err(dbus::MethodErr::failed("Client not connected to D-Bus")),
        }
    }
    /**
        a method

        Args:
            value: the value

        Returns:
            the return type
     */
    pub async fn uint32_method(&self, value: u32, ) -> Result<(u32,), dbus::MethodErr> {
        match &self.connection {
            Some(c) => {
                let proxy = Proxy::new("com.yarpc.backend", "/com/yarpc/backend/withArgs", self.timeout, c.clone());
                match proxy.method_call::<(u32,), (u32, ), _, _>("com.yarpc.backend.primitives", "Uint32Method", (value, )).await {
                    Ok(r) => Ok(r),
                    Err(e) => Err(dbus::MethodErr::from(e))
                }
            },
            None => Err(dbus::MethodErr::failed("Client not connected to D-Bus")),
        }
    }
    /**
        a method

        Args:
            value: the value

        Returns:
            the return type
     */
    pub async fn int64_method(&self, value: i64, ) -> Result<(i64,), dbus::MethodErr> {
        match &self.connection {
            Some(c) => {
                let proxy = Proxy::new("com.yarpc.backend", "/com/yarpc/backend/withArgs", self.timeout, c.clone());
                match proxy.method_call::<(i64,), (i64, ), _, _>("com.yarpc.backend.primitives", "Int64Method", (value, )).await {
                    Ok(r) => Ok(r),
                    Err(e) => Err(dbus::MethodErr::from(e))
                }
            },
            None => Err(dbus::MethodErr::failed("Client not connected to D-Bus")),
        }
    }
    /**
        a method

        Args:
            value: the value

        Returns:
            the return type
     */
    pub async fn uint64_method(&self, value: u64, ) -> Result<(u64,), dbus::MethodErr> {
        match &self.connection {
            Some(c) => {
                let proxy = Proxy::new("com.yarpc.backend", "/com/yarpc/backend/withArgs", self.timeout, c.clone());
                match proxy.method_call::<(u64,), (u64, ), _, _>("com.yarpc.backend.primitives", "Uint64Method", (value, )).await {
                    Ok(r) => Ok(r),
                    Err(e) => Err(dbus::MethodErr::from(e))
                }
            },
            None => Err(dbus::MethodErr::failed("Client not connected to D-Bus")),
        }
    }
    /**
        a method

        Args:
            value: the value

        Returns:
            the return type
     */
    pub async fn double_method(&self, value: f64, ) -> Result<(f64,), dbus::MethodErr> {
        match &self.connection {
            Some(c) => {
                let proxy = Proxy::new("com.yarpc.backend", "/com/yarpc/backend/withArgs", self.timeout, c.clone());
                match proxy.method_call::<(f64,), (f64, ), _, _>("com.yarpc.backend.primitives", "DoubleMethod", (value, )).await {
                    Ok(r) => Ok(r),
                    Err(e) => Err(dbus::MethodErr::from(e))
                }
            },
            None => Err(dbus::MethodErr::failed("Client not connected to D-Bus")),
        }
    }
    /**
        a method

        Args:
            value: the value

        Returns:
            the return type
     */
    pub async fn string_method(&self, value: String, ) -> Result<(String,), dbus::MethodErr> {
        match &self.connection {
            Some(c) => {
                let proxy = Proxy::new("com.yarpc.backend", "/com/yarpc/backend/withArgs", self.timeout, c.clone());
                match proxy.method_call::<(String,), (String, ), _, _>("com.yarpc.backend.primitives", "StringMethod", (value, )).await {
                    Ok(r) => Ok(r),
                    Err(e) => Err(dbus::MethodErr::from(e))
                }
            },
            None => Err(dbus::MethodErr::failed("Client not connected to D-Bus")),
        }
    }

}