// Generated by YARPC
// Version:  0.1.0
// Definition:
//   Files: ['/workspace/tests/definitions/rust/01_minimal.yml', '/workspace/tests/definitions/rust/02_with_args.yml']
//   Template: rust/connection.j2

#![allow(dead_code)]

use dbus_crossroads::Crossroads;
use futures::executor::block_on;
use tokio::task::JoinHandle;
use std::sync::{Arc, LazyLock};
use dbus::{message::MatchRule, nonblock::SyncConnection};
use dbus_tokio::connection;
use tokio::sync::Mutex;
use dbus::channel::{MatchingReceiver, Sender};

struct Connection {
    handle: JoinHandle<()>,
    connection: Arc<SyncConnection>,
    xr: Arc<Mutex<Crossroads>>,
}

impl Connection {
    pub async fn new() -> Result<Self, dbus::Error> {
        let (resource, connection) = connection::new_session_sync()?;
        let handle = tokio::spawn(async {
            let err = resource.await;
            panic!("Lost connection to D-Bus: {}", err);
        });
        Ok(Self{handle, connection,xr: Arc::new(Mutex::new(Crossroads::new()))})
    }

    pub fn connect(&self) -> Arc<SyncConnection> {
        self.connection.clone()
    }

    pub fn connection_count(&self) -> usize {
        Arc::<SyncConnection>::strong_count(&self.connection) - 2
    }
}

impl Drop for Connection {
fn drop(&mut self) {println!("DROP");}
}

static CONNECTION: LazyLock<Mutex<Option<Connection>>> = LazyLock::new(||{Mutex::new(None)});
static DEBUG: LazyLock<Mutex<String>> = LazyLock::new(||{
    println!("INIT ONCE");
    Mutex::new("None".to_string())
});

pub async fn connect() -> Result<Arc<SyncConnection>, dbus::Error> {
    let mut d = DEBUG.lock().await;
    if *d == "None" {
        print!("{} -> ",*d);
        *d = "Some".to_string();
    }
    println!("{}",*d);
    let mut guard = CONNECTION.lock().await;
    if guard.is_none() {
        let c = Connection::new().await?;
        *guard = Some(c);
    }
    let cloned_connection = (*guard).as_ref().unwrap().connect();
    Ok(cloned_connection)
}

pub async fn close() -> Result<(), dbus::Error> {
    println!("CLOSE IT");
    let mut guard = CONNECTION.lock().await;
    if (*guard).is_some() {
        let users = (*guard).as_ref().unwrap().connection_count();
        if users == 0  {
            *guard = None;
        } else {
            return Err(dbus::Error::new_failed(&format!("Unable to close. Connection is still used by {} clients.", users)));
        }
    }
    Ok(())
}

pub async fn get_xr() -> Result<Arc<Mutex<Crossroads>>, dbus::Error> {
    let mut d = DEBUG.lock().await;
    if *d == "None" {
        print!("{} -> ",*d);
        *d = "Some".to_string();
    }
    println!("{}",*d);
    let mut guard = CONNECTION.lock().await;
    if (*guard).is_none() {
        let c = Connection::new().await?;
        *guard = Some(c);
    }
    Ok(guard.as_ref().unwrap().xr.clone())
}

pub async fn start_receive() {
    let d = DEBUG.lock().await;
    println!("{}",*d);
    let guard = CONNECTION.lock().await;
    if guard.is_some() {
        let c = (*guard).as_ref().unwrap();
        let xr = c.xr.clone();
        c.connection.start_receive(MatchRule::new_method_call(), Box::new(move |msg, conn| {
            let mut unlocked_xr = block_on(xr.lock());
            unlocked_xr.handle_message(msg, conn).unwrap();
            true
        }));
        c.connection.request_name("com.yarpc.testservice", false, true, false).await;
    }
}