// Generated by YARPC
// Version:  0.1.0
// Definition:
//   File: /workspace/tests/definitions/02.2_primitives.yml
//   Object: Primitives
//   Template: rust/service.j2

#![allow(dead_code)]

use std::sync::Arc;
use async_trait::async_trait;
use dbus::nonblock::{SyncConnection};
use dbus_crossroads::Crossroads;
use tokio::sync::{RwLock};
use dbus::channel::{MatchingReceiver, Sender};
use dbus::message::MatchRule;
use dbus::{Message};
use super::connection::{connect};

#[async_trait]
pub trait PrimitivesInterfaceHandlers: Sync+Send {
    async fn handle_uint8_method(&self, value: u8, ) -> Result<(u8,) ,dbus::MethodErr>;
    async fn handle_bool_method(&self, value: bool, ) -> Result<(bool,) ,dbus::MethodErr>;
    async fn handle_int16_method(&self, value: i16, ) -> Result<(i16,) ,dbus::MethodErr>;
    async fn handle_uint16_method(&self, value: u16, ) -> Result<(u16,) ,dbus::MethodErr>;
    async fn handle_int32_method(&self, value: i32, ) -> Result<(i32,) ,dbus::MethodErr>;
    async fn handle_uint32_method(&self, value: u32, ) -> Result<(u32,) ,dbus::MethodErr>;
    async fn handle_int64_method(&self, value: i64, ) -> Result<(i64,) ,dbus::MethodErr>;
    async fn handle_uint64_method(&self, value: u64, ) -> Result<(u64,) ,dbus::MethodErr>;
    async fn handle_double_method(&self, value: f64, ) -> Result<(f64,) ,dbus::MethodErr>;
    async fn handle_string_method(&self, value: String, ) -> Result<(String,) ,dbus::MethodErr>;
}
type SharedOptionalHandlers = Arc<RwLock<Option<Arc<RwLock<dyn PrimitivesInterfaceHandlers>>>>>;

pub struct PrimitivesInterface {
    connection: Option<Arc<SyncConnection>>,
    handlers: SharedOptionalHandlers,
}

impl Clone for PrimitivesInterface {
    fn clone(&self) -> PrimitivesInterface {
        PrimitivesInterface{connection: self.connection.clone(), handlers: self.handlers.clone()}
    }
}


impl PrimitivesInterface {
    pub async fn connect() -> Result<Self, dbus::Error> {
        PrimitivesInterface::_connect(None).await
    }

    pub async fn connect_with_handlers(handlers: Arc<RwLock<dyn PrimitivesInterfaceHandlers>>) -> Result<Self, dbus::Error> {
        PrimitivesInterface::_connect(Some(handlers)).await
    }

    async fn _connect(handlers: Option<Arc<RwLock<dyn PrimitivesInterfaceHandlers>>>) -> Result<Self, dbus::Error> {
        let mut xr = Crossroads::new();
        let connection = connect().await?;

        let x = Self{
            connection: Some(connection.clone()),
            handlers: Arc::new(RwLock::new(handlers))
        };

        // Enable async support for xr instance
        xr.set_async_support(Some((connection.clone(), Box::new(|x| {tokio::spawn(x);}))));
        let iface_token = xr.register("com.yarpc.testservice.primitives", |b| {

            // advertise signals in introspection
            b.signal::<(u8, ), _>("Uint8Signal", ("value", ));
            b.signal::<(bool, ), _>("BoolSignal", ("value", ));
            b.signal::<(i16, ), _>("Int16Signal", ("value", ));
            b.signal::<(u16, ), _>("Uint16Signal", ("value", ));
            b.signal::<(i32, ), _>("Int32Signal", ("value", ));
            b.signal::<(u32, ), _>("Uint32Signal", ("value", ));
            b.signal::<(i64, ), _>("Int64Signal", ("value", ));
            b.signal::<(u64, ), _>("Uint64Signal", ("value", ));
            b.signal::<(f64, ), _>("DoubleSignal", ("value", ));
            b.signal::<(String, ), _>("StringSignal", ("value", ));

            // set up method handlers
            b.method_with_cr_async("Uint8Method", ("value", ), ("reply",), |mut ctx, xr, (value, ): (u8, )| {
                let handlers: &mut SharedOptionalHandlers = xr.data_mut(ctx.path()).unwrap();
                let cloned_handlers = handlers.clone();
                async move {
                    let optional_handlers = cloned_handlers.read().await;
                    match optional_handlers.as_ref() {
                        Some(h) => {
                            let unlocked_handlers = h.read().await;
                            ctx.reply(unlocked_handlers.handle_uint8_method(value, ).await)
                        },
                        None => ctx.reply(Err(dbus::MethodErr::failed("Not implemented")))
                    }
                }
            });
            b.method_with_cr_async("BoolMethod", ("value", ), ("reply",), |mut ctx, xr, (value, ): (bool, )| {
                let handlers: &mut SharedOptionalHandlers = xr.data_mut(ctx.path()).unwrap();
                let cloned_handlers = handlers.clone();
                async move {
                    let optional_handlers = cloned_handlers.read().await;
                    match optional_handlers.as_ref() {
                        Some(h) => {
                            let unlocked_handlers = h.read().await;
                            ctx.reply(unlocked_handlers.handle_bool_method(value, ).await)
                        },
                        None => ctx.reply(Err(dbus::MethodErr::failed("Not implemented")))
                    }
                }
            });
            b.method_with_cr_async("Int16Method", ("value", ), ("reply",), |mut ctx, xr, (value, ): (i16, )| {
                let handlers: &mut SharedOptionalHandlers = xr.data_mut(ctx.path()).unwrap();
                let cloned_handlers = handlers.clone();
                async move {
                    let optional_handlers = cloned_handlers.read().await;
                    match optional_handlers.as_ref() {
                        Some(h) => {
                            let unlocked_handlers = h.read().await;
                            ctx.reply(unlocked_handlers.handle_int16_method(value, ).await)
                        },
                        None => ctx.reply(Err(dbus::MethodErr::failed("Not implemented")))
                    }
                }
            });
            b.method_with_cr_async("Uint16Method", ("value", ), ("reply",), |mut ctx, xr, (value, ): (u16, )| {
                let handlers: &mut SharedOptionalHandlers = xr.data_mut(ctx.path()).unwrap();
                let cloned_handlers = handlers.clone();
                async move {
                    let optional_handlers = cloned_handlers.read().await;
                    match optional_handlers.as_ref() {
                        Some(h) => {
                            let unlocked_handlers = h.read().await;
                            ctx.reply(unlocked_handlers.handle_uint16_method(value, ).await)
                        },
                        None => ctx.reply(Err(dbus::MethodErr::failed("Not implemented")))
                    }
                }
            });
            b.method_with_cr_async("Int32Method", ("value", ), ("reply",), |mut ctx, xr, (value, ): (i32, )| {
                let handlers: &mut SharedOptionalHandlers = xr.data_mut(ctx.path()).unwrap();
                let cloned_handlers = handlers.clone();
                async move {
                    let optional_handlers = cloned_handlers.read().await;
                    match optional_handlers.as_ref() {
                        Some(h) => {
                            let unlocked_handlers = h.read().await;
                            ctx.reply(unlocked_handlers.handle_int32_method(value, ).await)
                        },
                        None => ctx.reply(Err(dbus::MethodErr::failed("Not implemented")))
                    }
                }
            });
            b.method_with_cr_async("Uint32Method", ("value", ), ("reply",), |mut ctx, xr, (value, ): (u32, )| {
                let handlers: &mut SharedOptionalHandlers = xr.data_mut(ctx.path()).unwrap();
                let cloned_handlers = handlers.clone();
                async move {
                    let optional_handlers = cloned_handlers.read().await;
                    match optional_handlers.as_ref() {
                        Some(h) => {
                            let unlocked_handlers = h.read().await;
                            ctx.reply(unlocked_handlers.handle_uint32_method(value, ).await)
                        },
                        None => ctx.reply(Err(dbus::MethodErr::failed("Not implemented")))
                    }
                }
            });
            b.method_with_cr_async("Int64Method", ("value", ), ("reply",), |mut ctx, xr, (value, ): (i64, )| {
                let handlers: &mut SharedOptionalHandlers = xr.data_mut(ctx.path()).unwrap();
                let cloned_handlers = handlers.clone();
                async move {
                    let optional_handlers = cloned_handlers.read().await;
                    match optional_handlers.as_ref() {
                        Some(h) => {
                            let unlocked_handlers = h.read().await;
                            ctx.reply(unlocked_handlers.handle_int64_method(value, ).await)
                        },
                        None => ctx.reply(Err(dbus::MethodErr::failed("Not implemented")))
                    }
                }
            });
            b.method_with_cr_async("Uint64Method", ("value", ), ("reply",), |mut ctx, xr, (value, ): (u64, )| {
                let handlers: &mut SharedOptionalHandlers = xr.data_mut(ctx.path()).unwrap();
                let cloned_handlers = handlers.clone();
                async move {
                    let optional_handlers = cloned_handlers.read().await;
                    match optional_handlers.as_ref() {
                        Some(h) => {
                            let unlocked_handlers = h.read().await;
                            ctx.reply(unlocked_handlers.handle_uint64_method(value, ).await)
                        },
                        None => ctx.reply(Err(dbus::MethodErr::failed("Not implemented")))
                    }
                }
            });
            b.method_with_cr_async("DoubleMethod", ("value", ), ("reply",), |mut ctx, xr, (value, ): (f64, )| {
                let handlers: &mut SharedOptionalHandlers = xr.data_mut(ctx.path()).unwrap();
                let cloned_handlers = handlers.clone();
                async move {
                    let optional_handlers = cloned_handlers.read().await;
                    match optional_handlers.as_ref() {
                        Some(h) => {
                            let unlocked_handlers = h.read().await;
                            ctx.reply(unlocked_handlers.handle_double_method(value, ).await)
                        },
                        None => ctx.reply(Err(dbus::MethodErr::failed("Not implemented")))
                    }
                }
            });
            b.method_with_cr_async("StringMethod", ("value", ), ("reply",), |mut ctx, xr, (value, ): (String, )| {
                let handlers: &mut SharedOptionalHandlers = xr.data_mut(ctx.path()).unwrap();
                let cloned_handlers = handlers.clone();
                async move {
                    let optional_handlers = cloned_handlers.read().await;
                    match optional_handlers.as_ref() {
                        Some(h) => {
                            let unlocked_handlers = h.read().await;
                            ctx.reply(unlocked_handlers.handle_string_method(value, ).await)
                        },
                        None => ctx.reply(Err(dbus::MethodErr::failed("Not implemented")))
                    }
                }
            });
        });

        xr.insert("/com/yarpc/testservice/withArgs", &[iface_token], x.handlers.clone());
        connection.start_receive(MatchRule::new_method_call(), Box::new(move |msg, conn| {
            xr.handle_message(msg, conn).unwrap();
            true
        }));

        connection.request_name("com.yarpc.testservice", false, true, false).await?;
        Ok(x)
    }

    pub async fn set_method_handlers(&self, handlers: Arc<RwLock<dyn PrimitivesInterfaceHandlers>>) {
        *(self.handlers.write().await) = Some(handlers);
    }

    pub fn emit_uint8_signal(&self, value: u8, ) {
        let mut signal = Message::signal(&"/com/yarpc/testservice/withArgs".into(), &"com.yarpc.testservice.primitives".into(), &"Uint8Signal".into());
        signal.append_all((value, ));
        if self.connection.is_some() {
            let _ = self.connection.as_ref().unwrap().send(signal);
        }
    }
    pub fn emit_bool_signal(&self, value: bool, ) {
        let mut signal = Message::signal(&"/com/yarpc/testservice/withArgs".into(), &"com.yarpc.testservice.primitives".into(), &"BoolSignal".into());
        signal.append_all((value, ));
        if self.connection.is_some() {
            let _ = self.connection.as_ref().unwrap().send(signal);
        }
    }
    pub fn emit_int16_signal(&self, value: i16, ) {
        let mut signal = Message::signal(&"/com/yarpc/testservice/withArgs".into(), &"com.yarpc.testservice.primitives".into(), &"Int16Signal".into());
        signal.append_all((value, ));
        if self.connection.is_some() {
            let _ = self.connection.as_ref().unwrap().send(signal);
        }
    }
    pub fn emit_uint16_signal(&self, value: u16, ) {
        let mut signal = Message::signal(&"/com/yarpc/testservice/withArgs".into(), &"com.yarpc.testservice.primitives".into(), &"Uint16Signal".into());
        signal.append_all((value, ));
        if self.connection.is_some() {
            let _ = self.connection.as_ref().unwrap().send(signal);
        }
    }
    pub fn emit_int32_signal(&self, value: i32, ) {
        let mut signal = Message::signal(&"/com/yarpc/testservice/withArgs".into(), &"com.yarpc.testservice.primitives".into(), &"Int32Signal".into());
        signal.append_all((value, ));
        if self.connection.is_some() {
            let _ = self.connection.as_ref().unwrap().send(signal);
        }
    }
    pub fn emit_uint32_signal(&self, value: u32, ) {
        let mut signal = Message::signal(&"/com/yarpc/testservice/withArgs".into(), &"com.yarpc.testservice.primitives".into(), &"Uint32Signal".into());
        signal.append_all((value, ));
        if self.connection.is_some() {
            let _ = self.connection.as_ref().unwrap().send(signal);
        }
    }
    pub fn emit_int64_signal(&self, value: i64, ) {
        let mut signal = Message::signal(&"/com/yarpc/testservice/withArgs".into(), &"com.yarpc.testservice.primitives".into(), &"Int64Signal".into());
        signal.append_all((value, ));
        if self.connection.is_some() {
            let _ = self.connection.as_ref().unwrap().send(signal);
        }
    }
    pub fn emit_uint64_signal(&self, value: u64, ) {
        let mut signal = Message::signal(&"/com/yarpc/testservice/withArgs".into(), &"com.yarpc.testservice.primitives".into(), &"Uint64Signal".into());
        signal.append_all((value, ));
        if self.connection.is_some() {
            let _ = self.connection.as_ref().unwrap().send(signal);
        }
    }
    pub fn emit_double_signal(&self, value: f64, ) {
        let mut signal = Message::signal(&"/com/yarpc/testservice/withArgs".into(), &"com.yarpc.testservice.primitives".into(), &"DoubleSignal".into());
        signal.append_all((value, ));
        if self.connection.is_some() {
            let _ = self.connection.as_ref().unwrap().send(signal);
        }
    }
    pub fn emit_string_signal(&self, value: String, ) {
        let mut signal = Message::signal(&"/com/yarpc/testservice/withArgs".into(), &"com.yarpc.testservice.primitives".into(), &"StringSignal".into());
        signal.append_all((value, ));
        if self.connection.is_some() {
            let _ = self.connection.as_ref().unwrap().send(signal);
        }
    }

}