# Generated by YARPC
# Version:  0.1.0+editable
# Spec:
#   File: /workspace/tests/specs/structs.yml
#   Object: SimpleStruct
#   Template: py/struct.j2
from .item import Item

from dataclasses import dataclass

@dataclass
class SimpleStruct:
    """
    An order

    Args:
        item (Item): The item
        amount (int): the amount ordered
    """
    item: Item
    amount: int

    def to_dbus(self):
        """
        Marshals this object into an array compatible with dbus structs.

        Returns:
            list: the marshalled structure
        """
        return [
            [
                self.item.name,
                self.item.price,
            ],
            self.amount,
        ]

    def from_dbus(dbus_struct: list):
        """
        Attempts to unmarshal a D-Bus struct array into this dataclass

        Args:
            dbus_struct (list): the marshalled D-Bus struct as array

        Returns:
            SimpleStruct: the unmarshalled structure
        """
        return SimpleStruct(
            item=Item(
                name=dbus_struct[0][0],
                price=dbus_struct[0][1],
            ),
            amount=dbus_struct[1],
        )
