# Generated by YARPC
# Version:  0.1.0+editable
# Spec:
#   File: /workspace/tests/specs/04.2_arrays_with_structs.yml
#   Object: StructArray
#   Template: py/struct.j2

from dataclasses import dataclass
from typing import Sequence, Mapping

@dataclass
class StructArray:
    """
    A struct containing arrays

    Args:
        numbers (Sequence[Sequence[int]]): some numbers
    """
    numbers: Sequence[Sequence[int]]

    def to_dbus(self):
        """
        Marshals this object into an array compatible with dbus structs.

        Returns:
            list: the marshalled structure
        """
        return [
            [ [ x1 for x1 in x0 ] for x0 in self.numbers ],
        ]

    def from_dbus(dbus_struct: list):
        """
        Attempts to unmarshal a D-Bus struct array into this dataclass

        Args:
            dbus_struct (list): the marshalled D-Bus struct as array

        Returns:
            StructArray: the unmarshalled structure
        """
        return StructArray(
            numbers=[ [ x1 for x1 in x0 ] for x0 in dbus_struct[0] ],
        )
