# Generated by YARPC
# Version:  0.1.0+editable
# Definition:
#   File: /workspace/tests/definitions/05.2_dictionaries_with_structs.yml
#   Object: DictsWithStructs
#   Template: py/client_mock.j2

from typing import List, Dict
from .connection import Connection
from dbus_next import Variant, DBusError
from unittest.mock import Mock
import sys
import asyncio
from .struct_dict import StructDict
from .simons_dict import SimonsDict


class DictsWithStructsClientMock():
    """
    Mock client implementation of the DictsWithStructs D-Bus interface

    The Mock instance can be accessed via the `mock` attribute.
    All received signals will be forwarded to the mock using keyword arguments.
    E.g.
    A received signal `Fooed('bar')`
    might result in the following call of the mock:
    `client.mock.Fooed(msg='bar')`
    """

    def __init__(self):
        self.name = "com.yarpc.testservice.dictsWithStructs"
        self._interface = None
        self._property_interface = None
        self.mock = Mock()

    async def connect(self):
        """
        Initializes the D-Bus connection and waits until it is closed
        """
        try:
            bus = await Connection.bus()
            introspection = await bus.introspect(
                "com.yarpc.testservice",
                "/com/yarpc/testservice",
            )
            proxy_object = bus.get_proxy_object(
                "com.yarpc.testservice",
                "/com/yarpc/testservice",
                introspection
            )
            self._interface = proxy_object.get_interface(
                self.name
            )

            self._interface.on_dict_struct_signal(self._DictStructSignal_handler)

            self._property_interface = proxy_object.get_interface(
                "org.freedesktop.DBus.Properties"
            )
            if self._properties_changed_handler:
                self._property_interface.on_properties_changed(self._properties_changed_handler)

            await bus.wait_for_disconnect()
        except Exception as e:
            print(f"{type(e).__name__}: {e}", file=sys.stderr)

    def _unpack_prop(self, name, variant):
        prop_map = {
            "DictStructProperty": lambda value: { k0: StructDict.from_dbus(v0) for k0, v0 in value.items() },
        }
        if name in prop_map:
            return prop_map[name](variant.value)
        return None

    def _unpack_properties(self, packed_properties):
        return {
            key: self._unpack_prop(key, packed_properties[key])
            for key in packed_properties.keys()
        }

    async def get_all_properties(self) -> dict:
        """Getter for all properties

        Returns:
            dict: a dictionary containing the current state of all properties
        """
        properties = await self._property_interface.call_get_all(self.name)
        return self._unpack_properties(properties)

    def _properties_changed_handler(self, interface: str, properties: dict, _invalidated: list):
        if interface == self.name:
            properties = self._unpack_properties(properties)
            self.mock.on_properties_changed(properties=properties)

    async def DictsStructMethod(
        self,
        numbers: Dict[str, StructDict],
    ) -> Dict[str, SimonsDict]:
        """
        a simple method with one argument

        Args:
            numbers (Dict[str, StructDict]): Some numbers
        """
        while not self._interface:
            await asyncio.sleep(0.1)
        raw_return = await self._interface.call_dicts_struct_method(
            { k0: v0.to_dbus() for k0, v0 in numbers.items() },
        )
        return { k0: SimonsDict.from_dbus(v0) for k0, v0 in raw_return.items() }

    def _DictStructSignal_handler(
        self,
            numbers: 'a{s(a{sa{su}})}',
    ):
        self.mock.DictStructSignal(
            { k0: StructDict.from_dbus(v0) for k0, v0 in numbers.items() },
        )

    async def get_DictStructProperty(self) -> Dict[str, StructDict]:
        """Getter for property 'DictStructProperty'

        a simple property

        Returns:
            Dict[str, StructDict]: the current value
        """
        while not self._interface:
            await asyncio.sleep(0.1)
        raw_return = await self._interface.get_dict_struct_property()
        unmarshalled = { k0: StructDict.from_dbus(v0) for k0, v0 in raw_return.items() }
        return unmarshalled

    async def set_DictStructProperty(self, value: Dict[str, StructDict]) -> None:
        """Setter for property 'DictStructProperty'

        a simple property

        Args:
            value (Dict[str, StructDict]): the new value
        """
        while not self._interface:
            await asyncio.sleep(0.1)
        marshalled = { k0: v0.to_dbus() for k0, v0 in value.items() }
        return await self._interface.set_dict_struct_property(marshalled)
