# Generated by YARPC
# Version:  0.1.0+editable
# Spec:
#   File: /workspace/tests/specs/05.2_dictionaries_with_structs.yml
#   Object: StructDict
#   Template: py/struct.j2

from dataclasses import dataclass
from typing import Sequence, Mapping

@dataclass
class StructDict:
    """
    A struct containing dicts

    Args:
        numbers (Mapping[str, Mapping[str, int]]): some numbers
    """
    numbers: Mapping[str, Mapping[str, int]]

    def to_dbus(self):
        """
        Marshals this object into an array compatible with dbus structs.

        Returns:
            list: the marshalled structure
        """
        return [
            { k0: { k1: v1 for k1, v1 in v0.items() } for k0, v0 in self.numbers.items() },
        ]

    def from_dbus(dbus_struct: list):
        """
        Attempts to unmarshal a D-Bus struct array into this dataclass

        Args:
            dbus_struct (list): the marshalled D-Bus struct as array

        Returns:
            StructDict: the unmarshalled structure
        """
        return StructDict(
            numbers={ k0: { k1: v1 for k1, v1 in v0.items() } for k0, v0 in dbus_struct[0].items() },
        )
