# Generated by YARPC
# Version:  0.1.0
# Definition:
#   File: /workspace/tests/definitions/06.1_enums.yml
#   Object: Color
#   Template: py/enum.j2

from enum import Enum

class Color(Enum):
    """
    A enum of colors
    """
    RED = 0
    GREEN = 1
    BLUE = 2
    ORANGE = 3
