# Generated by YARPC
# Version:  0.1.0
# Definition:
#   File: /workspace/tests/definitions/06.1_enums.yml
#   Object: Enums
#   Template: py/service.j2

from typing import Protocol, List, Dict
from dbus_next.service import (
    ServiceInterface, method, dbus_property, signal
)
from dbus_next.constants import PropertyAccess
from dbus_next import Variant, DBusError
from copy import deepcopy
from enum import Enum
from .enum_struct import EnumStruct
from .color import Color


class ProvidesEnumsInterfaceProperties(Protocol):
    """Protocol for property providers of EnumsInterface
    """

    async def get_EnumProperty(self) -> Color:
        """Getter for EnumProperty property

        Returns:
            Color: the current value
        """
        ...

    async def set_EnumProperty(self, value: Color) -> dict:
        """Setter for EnumProperty property

        Args:
            value (Color): the new value

        Returns:
            dict: dictionary of the changed properties, empty if None changed
        """
        ...


class EnumsInterfaceProperties:
    """Manages the state of the properties for EnumsInterface

    Args:
        EnumProperty (Color): a property
    """

    def __init__(
        self,
        EnumProperty: Color,
    ):
        self._properties = {
            "EnumProperty": EnumProperty,
        }

    async def get_EnumProperty(self) -> Color:
        """Getter for EnumProperty property

        Returns:
            Color: the current value
        """
        return self._properties["EnumProperty"]

    async def set_EnumProperty(self, value: Color) -> dict:
        """Setter for EnumProperty property

        Args:
            value (Color): the new value

        Returns:
            dict: dictionary of the changed properties, empty if None changed
        """
        if value == self._properties["EnumProperty"]:
            return {}
        self._properties["EnumProperty"] = value
        return {"EnumProperty": value}


class _Interface(ServiceInterface):
    """
    D-Bus interface implementation for Enums

    Args:
        wrapper(EnumsInterface): Wrapper responsible for (un-)marhsalling D-Bus types
    """

    def __init__(self, wrapper):
        super().__init__("com.yarpc.testservice.enums")
        self.object_path = "/com/yarpc/testservice/enums"
        self._wrapper = wrapper

    @method()
    async def EnumMethod(
        self,
        color: 'i',
    ) -> 'i':
        raw_return = await self._wrapper.EnumMethod(
            Color(color),
        )
        return raw_return.value

    @signal()
    def EnumSignal(
        self,
        color: 'i',
    ) -> 'i':
        return color

    @dbus_property(access=PropertyAccess.READWRITE)
    async def EnumProperty(self) -> 'i':
        unmarshalled = await self._wrapper.get_EnumProperty()
        return unmarshalled.value

    @EnumProperty.setter
    async def EnumProperty(self, value: 'i'):
        unmarshalled = Color(value)
        await self._wrapper.set_EnumProperty(unmarshalled)


class EnumsInterface():
    """
    A interface using enums

    Args:
        property_provider (ProvidesEnumsInterfaceProperties): provider for interface properties
    """

    def __init__(
        self,
        property_provider: ProvidesEnumsInterfaceProperties,
    ):
        self.interface = _Interface(self)
        self.name = self.interface.name
        self.object_path = self.interface.object_path

        self._EnumMethod_handler = None
        self._properties = property_provider

    def emit_properties_changed(self, changed_properties: dict) -> None:
        """Informs clients about changed properties

        Args:
            changed_properties (dict): A dictionary containing all changed properties with their new values
        """
        if not changed_properties: return

        def marshal(data):
            if isinstance(data, dict):
                new_data = {}
                for key in data.keys():
                    new_data[key.value if isinstance(key, Enum) else key] = marshal(data[key])
                return new_data
            elif isinstance(data, list):
                for i in range(0, len(data)):
                    data[i] = marshal(data[i])
                return data
            elif isinstance(data, Enum):
                return data.value
            elif hasattr(data, 'to_dbus'):
                return data.to_dbus()
            else:
                return data
        marshalled = marshal(deepcopy(changed_properties))
        self.interface.emit_properties_changed(marshalled)

    def on_EnumMethod(self, handler) -> None:
        """
        Set handler for EnumMethod method

        Args:
            handler (Callable[[Color], Awaitable[Color]]): the method handler
        """
        self._EnumMethod_handler = handler

    async def EnumMethod(
        self,
        color: Color,
    ) -> Color:
        """
        a simple method with one argument

        Args:
            color (Color): a color

        Returns:
            Color: another color
        """
        if self._EnumMethod_handler is None:
            raise NotImplementedError()

        return await self._EnumMethod_handler(
            color,
        )

    def EnumSignal(
        self,
        color: Color,
    ) -> None:
        """
        a simple signal with one argument

        Args:
            color (Color): a color
        """
        self.interface.EnumSignal(
            color.value,
        )

    async def get_EnumProperty(self) -> Color:
        """Getter for property EnumProperty

        a property

        Returns:
            Color: the current value
        """
        return await self._properties.get_EnumProperty()

    async def set_EnumProperty(self, value: Color):
        """Setter for property EnumProperty

        a property

        Args:
            value (Color): the new value
        """
        changed_properties = await self._properties.set_EnumProperty(value)

        self.emit_properties_changed(changed_properties)
