# Generated by YARPC
# Version:  0.1.0+editable
# Definition:
#   File: /workspace/tests/definitions/06.3_enums_with_dicts.yml
#   Object: EnumsWithDicts
#   Template: py/service.j2

from typing import Protocol, List, Dict
from dbus_next.service import (
    ServiceInterface, method, dbus_property, signal
)
from dbus_next.constants import PropertyAccess
from dbus_next import Variant, DBusError
from copy import deepcopy
from enum import Enum
from .enum_struct import EnumStruct
from .color import Color


class ProvidesEnumsWithDictsInterfaceProperties(Protocol):
    """Protocol for property providers of EnumsWithDictsInterface
    """

    async def get_EnumProperty(self) -> Dict[Color, Color]:
        """Getter for EnumProperty property

        Returns:
            Dict[Color, Color]: the current value
        """
        ...

    async def set_EnumProperty(self, value: Dict[Color, Color]) -> dict:
        """Setter for EnumProperty property

        Args:
            value (Dict[Color, Color]): the new value

        Returns:
            dict: dictionary of the changed properties, empty if None changed
        """
        ...


class EnumsWithDictsInterfaceProperties:
    """Manages the state of the properties for EnumsWithDictsInterface

    Args:
        EnumProperty (Dict[Color, Color]): a property
    """

    def __init__(
        self,
        EnumProperty: Dict[Color, Color],
    ):
        self._properties = {
            "EnumProperty": EnumProperty,
        }

    async def get_EnumProperty(self) -> Dict[Color, Color]:
        """Getter for EnumProperty property

        Returns:
            Dict[Color, Color]: the current value
        """
        return self._properties["EnumProperty"]

    async def set_EnumProperty(self, value: Dict[Color, Color]) -> dict:
        """Setter for EnumProperty property

        Args:
            value (Dict[Color, Color]): the new value

        Returns:
            dict: dictionary of the changed properties, empty if None changed
        """
        if value == self._properties["EnumProperty"]:
            return {}
        self._properties["EnumProperty"] = value
        return {"EnumProperty": value}


class _Interface(ServiceInterface):
    """
    D-Bus interface implementation for EnumsWithDicts

    Args:
        wrapper(EnumsWithDictsInterface): Wrapper responsible for (un-)marhsalling D-Bus types
    """

    def __init__(self, wrapper):
        super().__init__("com.yarpc.testservice.enumsWithDicts")
        self.object_path = "/com/yarpc/testservice"
        self._wrapper = wrapper

    @method()
    async def EnumMethod(
        self,
        color: 'a{ii}',
    ) -> 'a{ii}':
        raw_return = await self._wrapper.EnumMethod(
            { Color(k0): Color(v0) for k0, v0 in color.items() },
        )
        return { k0.value: v0.value for k0, v0 in raw_return.items() }

    @signal()
    def EnumSignal(
        self,
        color: 'a{ii}',
    ) -> 'a{ii}':
        return color

    @dbus_property(access=PropertyAccess.READWRITE)
    async def EnumProperty(self) -> 'a{ii}':
        unmarshalled = await self._wrapper.get_EnumProperty()
        return { k0.value: v0.value for k0, v0 in unmarshalled.items() }

    @EnumProperty.setter
    async def EnumProperty(self, value: 'a{ii}'):
        unmarshalled = { Color(k0): Color(v0) for k0, v0 in value.items() }
        await self._wrapper.set_EnumProperty(unmarshalled)


class EnumsWithDictsInterface():
    """
    A interface using enums in dictionaries

    Args:
        property_provider (ProvidesEnumsWithDictsInterfaceProperties): provider for interface properties
    """

    def __init__(
        self,
        property_provider: ProvidesEnumsWithDictsInterfaceProperties,
    ):
        self.interface = _Interface(self)
        self.name = self.interface.name
        self.object_path = self.interface.object_path

        self._EnumMethod_handler = None
        self._properties = property_provider

    def emit_properties_changed(self, changed_properties: dict) -> None:
        """Informs clients about changed properties

        Args:
            changed_properties (dict): A dictionary containing all changed properties with their new values
        """
        if not changed_properties: return

        def marshal(data):
            if isinstance(data, dict):
                new_data = {}
                for key in data.keys():
                    new_data[key.value if isinstance(key, Enum) else key] = marshal(data[key])
                return new_data
            elif isinstance(data, list):
                for i in range(0, len(data)):
                    data[i] = marshal(data[i])
                return data
            elif isinstance(data, Enum):
                return data.value
            elif hasattr(data, 'to_dbus'):
                return data.to_dbus()
            else:
                return data
        marshalled = marshal(deepcopy(changed_properties))
        self.interface.emit_properties_changed(marshalled)

    def on_EnumMethod(self, handler) -> None:
        """
        Set handler for EnumMethod method

        Args:
            handler (Callable[[Dict[Color, Color]], Awaitable[Dict[Color, Color]]]): the method handler
        """
        self._EnumMethod_handler = handler

    async def EnumMethod(
        self,
        color: Dict[Color, Color],
    ) -> Dict[Color, Color]:
        """
        a simple method with one argument

        Args:
            color (Dict[Color, Color]): a color

        Returns:
            Dict[Color, Color]: another color
        """
        if self._EnumMethod_handler is None:
            raise NotImplementedError()

        return await self._EnumMethod_handler(
            color,
        )

    def EnumSignal(
        self,
        color: Dict[Color, Color],
    ) -> None:
        """
        a simple signal with one argument

        Args:
            color (Dict[Color, Color]): a color
        """
        self.interface.EnumSignal(
            { k0.value: v0.value for k0, v0 in color.items() },
        )

    async def get_EnumProperty(self) -> Dict[Color, Color]:
        """Getter for property EnumProperty

        a property

        Returns:
            Dict[Color, Color]: the current value
        """
        return await self._properties.get_EnumProperty()

    async def set_EnumProperty(self, value: Dict[Color, Color]):
        """Setter for property EnumProperty

        a property

        Args:
            value (Dict[Color, Color]): the new value
        """
        changed_properties = await self._properties.set_EnumProperty(value)

        self.emit_properties_changed(changed_properties)
