# Generated by YARPC
# Version:  0.1.0+editable
# Spec:
#   File: /workspace/tests/specs/02_with_args.yml
#   Object: WithArgs
#   Template: py/service.j2

from typing import Protocol
from dbus_next.service import (
    ServiceInterface, method, dbus_property, signal
)
from dbus_next.constants import PropertyAccess
from dbus_next import Variant, DBusError


class ProvidesWithArgsInterfaceProperties(Protocol):
    """Protocol for property providers of WithArgsInterface
    """

    async def get_Speed(self) -> float:
        """Getter for Speed property

        Returns:
            float: the current value
        """
        ...

    async def set_Speed(self, value: float) -> dict:
        """Setter for Speed property

        Args:
            value (float): the new value

        Returns:
            dict: dictionary of the changed properties, empty if None changed
        """
        ...

    async def get_Distance(self) -> int:
        """Getter for Distance property

        Returns:
            int: the current value
        """
        ...

    async def set_Distance(self, value: int) -> dict:
        """Setter for Distance property

        Args:
            value (int): the new value

        Returns:
            dict: dictionary of the changed properties, empty if None changed
        """
        ...

    async def get_Duration(self) -> float:
        """Getter for Duration property

        Returns:
            float: the current value
        """
        ...

    async def set_Duration(self, value: float) -> dict:
        """Setter for Duration property

        Args:
            value (float): the new value

        Returns:
            dict: dictionary of the changed properties, empty if None changed
        """
        ...


class WithArgsInterfaceProperties:
    """Manages the state of the properties for WithArgsInterface

    Args:
        Speed (float): the speed in m/s
        Distance (int): the distance to travel in m
        Duration (float): the time until the distance is covered at the current speed
    """

    def __init__(
        self,
        Speed: float,
        Distance: int,
        Duration: float,
    ):
        self._properties = {
            "Speed": Speed,
            "Distance": Distance,
            "Duration": Duration,
        }

    async def get_Speed(self) -> float:
        """Getter for Speed property

        Returns:
            float: the current value
        """
        return self._properties["Speed"]

    async def set_Speed(self, value: float) -> dict:
        """Setter for Speed property

        Args:
            value (float): the new value

        Returns:
            dict: dictionary of the changed properties, empty if None changed
        """
        if value == self._properties["Speed"]:
            return {}
        self._properties["Speed"] = value
        return {"Speed": value}

    async def get_Distance(self) -> int:
        """Getter for Distance property

        Returns:
            int: the current value
        """
        return self._properties["Distance"]

    async def set_Distance(self, value: int) -> dict:
        """Setter for Distance property

        Args:
            value (int): the new value

        Returns:
            dict: dictionary of the changed properties, empty if None changed
        """
        if value == self._properties["Distance"]:
            return {}
        self._properties["Distance"] = value
        return {"Distance": value}

    async def get_Duration(self) -> float:
        """Getter for Duration property

        Returns:
            float: the current value
        """
        return self._properties["Duration"]

    async def set_Duration(self, value: float) -> dict:
        """Setter for Duration property

        Args:
            value (float): the new value

        Returns:
            dict: dictionary of the changed properties, empty if None changed
        """
        if value == self._properties["Duration"]:
            return {}
        self._properties["Duration"] = value
        return {"Duration": value}


class _Interface(ServiceInterface):
    """
    D-Bus interface implementation for WithArgs

    Args:
        wrapper(WithArgsInterface): Wrapper responsible for (un-)marhsalling D-Bus types
    """

    def __init__(self, wrapper):
        super().__init__("com.yarpc.testservice.withArgs")
        self.object_path = "/com/yarpc/testservice"
        self._wrapper = wrapper

    @signal()
    def Notified(
        self,
        message: 's',
    ) -> 's':
        return message

    @signal()
    def OrderReceived(
        self,
        item: 's',
        amount: 'u',
        pricePerItem: 'd',
    ) -> 'sud':
        return [
            item,
            amount,
            pricePerItem,
        ]

    @method()
    async def Notify(
        self,
        message: 's',
    ) -> None:
        await self._wrapper.Notify(
            message,
        )
        return None

    @method()
    async def Order(
        self,
        item: 's',
        amount: 'u',
        pricePerItem: 'd',
    ) -> 'd':
        raw_return = await self._wrapper.Order(
            item,
            amount,
            pricePerItem,
        )
        return raw_return

    @dbus_property(access=PropertyAccess.READWRITE)
    async def Speed(self) -> 'd':
        unmarshalled = await self._wrapper.get_Speed()
        return unmarshalled

    @Speed.setter
    async def Speed(self, value: 'd'):
        unmarshalled = value
        await self._wrapper.set_Speed(unmarshalled)

    @dbus_property(access=PropertyAccess.READWRITE)
    async def Distance(self) -> 'u':
        unmarshalled = await self._wrapper.get_Distance()
        return unmarshalled

    @Distance.setter
    async def Distance(self, value: 'u'):
        unmarshalled = value
        await self._wrapper.set_Distance(unmarshalled)

    @dbus_property(access=PropertyAccess.READ)
    async def Duration(self) -> 'd':
        unmarshalled = await self._wrapper.get_Duration()
        return unmarshalled


class WithArgsInterface():
    """
    A interface using only primitive types

    Args:
        property_provider (ProvidesWithArgsInterfaceProperties): provider for interface properties
    """

    def __init__(
        self,
        property_provider: ProvidesWithArgsInterfaceProperties,
    ):
        self.interface = _Interface(self)
        self.name = self.interface.name
        self.object_path = self.interface.object_path

        self._Notify_handler = None
        self._Order_handler = None
        self._properties = property_provider

    def emit_properties_changed(self, changed_properties: dict) -> None:
        """Informs clients about changed properties

        Args:
            changed_properties (dict): A dictionary containing all changed properties with their new values
        """
        if not changed_properties: return

        def marshal(data):
            if isinstance(data, dict):
                for key in data.keys():
                    data[key] = marshal(data[key])
                return data
            elif isinstance(data, list):
                for i in range(0, len(data)):
                    data[i] = marshal(data[i])
                return data
            elif hasattr(data, 'to_dbus'):
                return data.to_dbus()
            else:
                return data
        marshalled = marshal(changed_properties)
        self.interface.emit_properties_changed(marshalled)

    def Notified(
        self,
        message: str,
    ) -> None:
        """
        a simple signal with one argument

        Args:
            message (str): The message
        """
        self.interface.Notified(
            message,
        )

    def OrderReceived(
        self,
        item: str,
        amount: int,
        pricePerItem: float,
    ) -> None:
        """
        a simple signal with multiple arguments

        Args:
            item (str): The item
            amount (int): a amount ordered
            pricePerItem (float): the price per item
        """
        self.interface.OrderReceived(
            item,
            amount,
            pricePerItem,
        )

    def on_Notify(self, handler) -> None:
        """
        Set handler for Notify method

        Args:
            handler (Callable[[str], Awaitable[None]]): the method handler
        """
        self._Notify_handler = handler

    async def Notify(
        self,
        message: str,
    ) -> None:
        """
        a simple method with one argument

        Args:
            message (str): The message
        """
        if self._Notify_handler is None:
            raise NotImplementedError()

        return await self._Notify_handler(
            message,
        )

    def on_Order(self, handler) -> None:
        """
        Set handler for Order method

        Args:
            handler (Callable[[str, int, float], Awaitable[float]]): the method handler
        """
        self._Order_handler = handler

    async def Order(
        self,
        item: str,
        amount: int,
        pricePerItem: float,
    ) -> float:
        """
        a simple method with args and return value

        Args:
            item (str): The item
            amount (int): a amount ordered
            pricePerItem (float): the price per item

        Returns:
            float: the total price
        """
        if self._Order_handler is None:
            raise NotImplementedError()

        return await self._Order_handler(
            item,
            amount,
            pricePerItem,
        )

    async def get_Speed(self) -> float:
        """Getter for property Speed

        the speed in m/s

        Returns:
            float: the current value
        """
        return await self._properties.get_Speed()

    async def set_Speed(self, value: float):
        """Setter for property Speed

        the speed in m/s

        Args:
            value (float): the new value
        """
        changed_properties = await self._properties.set_Speed(value)

        self.emit_properties_changed(changed_properties)

    async def get_Distance(self) -> int:
        """Getter for property Distance

        the distance to travel in m

        Returns:
            int: the current value
        """
        return await self._properties.get_Distance()

    async def set_Distance(self, value: int):
        """Setter for property Distance

        the distance to travel in m

        Args:
            value (int): the new value
        """
        changed_properties = await self._properties.set_Distance(value)

        self.emit_properties_changed(changed_properties)

    async def get_Duration(self) -> float:
        """Getter for property Duration

        the time until the distance is covered at the current speed

        Returns:
            float: the current value
        """
        return await self._properties.get_Duration()

    async def set_Duration(self, value: float):
        """Setter for property Duration

        the time until the distance is covered at the current speed

        Args:
            value (float): the new value
        """
        changed_properties = await self._properties.set_Duration(value)

        self.emit_properties_changed(changed_properties)
