name: CI Pipeline
on: [push]
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Cache docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Docker build
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.workspace }}/sdk
        builder: ${{ steps.buildx.outputs.name }}
        push: false
        tags: yarpc-sdk
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        outputs: type=docker,dest=/tmp/yarpc-sdk.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: yarpc-sdk
        path: /tmp/yarpc-sdk.tar
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  Build-And-Deploy-Pages:
    runs-on: ubuntu-latest
    needs: Build-Docker-Image
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Download SDK
      uses: actions/download-artifact@v4
      with:
        name: yarpc-sdk
        path: /tmp
    - name: Load SDK
      run: docker load --input /tmp/yarpc-sdk.tar
    - name: Build documentation
      run: bash ${{ github.workspace }}/sdk/run.sh ./docs/build.sh
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: ${{ github.workspace }}/docs/html
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    needs: Build-Docker-Image
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Download SDK
      uses: actions/download-artifact@v4
      with:
        name: yarpc-sdk
        path: /tmp
    - name: Load SDK
      run: docker load --input /tmp/yarpc-sdk.tar
    - name: Run unit tests
      run: bash ${{ github.workspace }}/sdk/run.sh ./yarpc/run_tests.sh
  Run-Python-Generator-Tests:
    runs-on: ubuntu-latest
    needs: Build-Docker-Image
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Download SDK
      uses: actions/download-artifact@v4
      with:
        name: yarpc-sdk
        path: /tmp
    - name: Load SDK
      run: docker load --input /tmp/yarpc-sdk.tar
    - name: Run behave tests
      run: bash ${{ github.workspace }}/sdk/run.sh ./tests/run_tests.sh python
  Run-Qt6-Generator-Tests:
    runs-on: ubuntu-latest
    needs: Build-Docker-Image
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Download SDK
      uses: actions/download-artifact@v4
      with:
        name: yarpc-sdk
        path: /tmp
    - name: Load SDK
      run: docker load --input /tmp/yarpc-sdk.tar
    - name: Run behave tests
      run: bash ${{ github.workspace }}/sdk/run.sh ./tests/run_tests.sh qt6